# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jeu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 569)
        MainWindow.setStyleSheet("#MainWindow {\n"
"    background-color: #448ccb ;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget {\n"
"    background-color: #448ccb ;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setGeometry(QtCore.QRect(90, 70, 551, 401))
        self.gridWidget.setStyleSheet("#gridWidget{\n"
"border-radius : 10px ;\n"
"padding : 10px ;\n"
"background-color : white ;\n"
"\n"
"}")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.line_2 = QtWidgets.QFrame(self.gridWidget)
        self.line_2.setBaseSize(QtCore.QSize(0, 43))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.gridWidget)
        self.line.setBaseSize(QtCore.QSize(0, 43))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.row2 = QtWidgets.QWidget(self.gridWidget)
        self.row2.setObjectName("row2")
        self.splitter_2 = QtWidgets.QSplitter(self.row2)
        self.splitter_2.setGeometry(QtCore.QRect(20, 20, 491, 91))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.pushButton4 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton4.setStyleSheet("QPushButton {\n"
"background : none ;\n"
"border:none;\n"
"}")
        self.pushButton4.setText("")
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton5 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton5.setStyleSheet("QPushButton {\n"
"background : none ;\n"
"border:none;\n"
"}")
        self.pushButton5.setText("")
        self.pushButton5.setObjectName("pushButton5")
        self.pushButton6 = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton6.setStyleSheet("QPushButton {\n"
"background : none ;\n"
"border:none;\n"
"}")
        self.pushButton6.setText("")
        self.pushButton6.setObjectName("pushButton6")
        self.gridLayout.addWidget(self.row2, 2, 0, 1, 1)
        self.row3 = QtWidgets.QWidget(self.gridWidget)
        self.row3.setObjectName("row3")
        self.splitter_3 = QtWidgets.QSplitter(self.row3)
        self.splitter_3.setGeometry(QtCore.QRect(20, 10, 491, 91))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.pushButton7 = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton7.setStyleSheet("QPushButton {\n"
"background : none ;\n"
"border:none;\n"
"}")
        self.pushButton7.setText("")
        self.pushButton7.setObjectName("pushButton7")
        self.pushButton8 = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton8.setStyleSheet("QPushButton {\n"
"background : none ;\n"
"border:none;\n"
"}")
        self.pushButton8.setText("")
        self.pushButton8.setObjectName("pushButton8")
        self.pushButton9 = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton9.setStyleSheet("QPushButton {\n"
"background : none ;\n"
"border:none;\n"
"}")
        self.pushButton9.setText("")
        self.pushButton9.setObjectName("pushButton9")
        self.gridLayout.addWidget(self.row3, 4, 0, 1, 1)
        self.row1 = QtWidgets.QWidget(self.gridWidget)
        self.row1.setObjectName("row1")
        self.splitter = QtWidgets.QSplitter(self.row1)
        self.splitter.setGeometry(QtCore.QRect(20, 20, 491, 91))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton1 = QtWidgets.QPushButton(self.splitter)
        self.pushButton1.setEnabled(True)
        self.pushButton1.setStyleSheet("QPushButton {\n"
"background : none ;\n"
"border:none;\n"
"image : url(:/Mes images/Design/cercle.png)\n"
"}")
        self.pushButton1.setText("")
        self.pushButton1.setCheckable(True)
        self.pushButton1.setAutoExclusive(False)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton2.setStyleSheet("QPushButton {\n"
"background : none ;\n"
"border:none;\n"
"}")
        self.pushButton2.setText("")
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(self.splitter)
        self.pushButton3.setStyleSheet("QPushButton {\n"
"background : none ;\n"
"border:none;\n"
"}")
        self.pushButton3.setText("")
        self.pushButton3.setObjectName("pushButton3")
        self.gridLayout.addWidget(self.row1, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 20, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(230, 490, 281, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgba(0, 0, 0,0.5);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(650, 220, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color : red ; ")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Au tour de Joueur 1"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MV Boli\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt;\">Joueur1 x - y Joueur2 </span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Manche 1"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
