# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(722, 666)
        MainWindow.setBaseSize(QtCore.QSize(722, 647))
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("#MainWindow{\n"
"    background-color : white ;\n"
"\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 20, 671, 591))
        self.widget.setMouseTracking(True)
        self.widget.setTabletTracking(True)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("#widget {\n"
"    \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(170, 170, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-radius : 5px ;\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(230, 20, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Niagara Engraved")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("#label {\n"
"background-color: rgba(255, 255, 255,0.5);\n"
"padding : 10px ;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(60, 150, 541, 101))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color : white ;\n"
"padding : 10px ;\n"
"border-radius : 2px ;")
        self.label_4.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(60, 320, 541, 201))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color : white ;\n"
"padding : 10px ;\n"
"border-radius : 2px ;")
        self.label_5.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(210, 540, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(40, 270, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        font.setUnderline(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 21))
        self.menubar.setObjectName("menubar")
        self.Partie = QtWidgets.QMenu(self.menubar)
        self.Partie.setTearOffEnabled(False)
        self.Partie.setObjectName("Partie")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionJeu = QtWidgets.QAction(MainWindow)
        self.actionJeu.setObjectName("actionJeu")
        self.actionA_propos = QtWidgets.QAction(MainWindow)
        self.actionA_propos.setObjectName("actionA_propos")
        self.Partie.addAction(self.actionJeu)
        self.Partie.addSeparator()
        self.Partie.addAction(self.actionA_propos)
        self.menubar.addAction(self.Partie.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Jeu de Tic Tac Toe"))
        self.label_2.setText(_translate("MainWindow", "BUT DU JEU"))
        self.label_4.setText(_translate("MainWindow", "Le but de ce jeu est d\'aligner 3 symboles de meme type , soit de facon oblique , soit de facon horizontale ou de facon verticale . \n"
" Le premier à reussir cet exploit remporte la manche ."))
        self.label_5.setText(_translate("MainWindow", "Comme vous l\'auriez deviner le jeu se joue à deux (deux joueurs ) \n"
"Le jeu se fait , suivant plusieurs manches , vous avez deja choisi le nombre de manches pour gagner une partie . \n"
" Les joueurs jouent tour à tour . \n"
" Il s\'agit de placer soit une croix soit un rond selon le joueur dans la grille du jeu , la grille est en fait un tableau de 3 colonnes et 3 lignes ."))
        self.label_6.setText(_translate("MainWindow", "AMUSEZ-VOUS BIEN"))
        self.label_3.setText(_translate("MainWindow", "DEROULEMENT DU JEU"))
        self.Partie.setTitle(_translate("MainWindow", "Menu"))
        self.actionJeu.setText(_translate("MainWindow", "Jeu"))
        self.actionJeu.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionA_propos.setText(_translate("MainWindow", "A propos"))
        self.actionA_propos.setShortcut(_translate("MainWindow", "Ctrl+P"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
