# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entree.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(488, 404)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("margin : 0px 0px ;\n"
"padding: 0px 0px ;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(170, 170, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"child {\n"
"background-color : none ;\n"
"}")
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 20, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Tempus Sans ITC")
        font.setPointSize(20)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color : none ;")
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(90, 69, 331, 271))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("QWidget #widget { \n"
"border : 2px solid black ;\n"
"background-color: #448ccb ;\n"
"border-radius : 10px ;\n"
"opacity : 75% ;\n"
"box-shadow : 2px ;\n"
"}\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalWidget_2 = QtWidgets.QWidget(self.widget)
        self.horizontalWidget_2.setGeometry(QtCore.QRect(0, 10, 331, 51))
        self.horizontalWidget_2.setStyleSheet("background-color : none ;")
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalWidget_2)
        self.horizontalLayout_2.setContentsMargins(50, 5, 50, 5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"border : none ;\n"
"background-color : none ;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalWidget_2)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255) ;\n"
"border : inherit ;\n"
"border-radius : 10px ;\n"
"font-size: 15px ;\n"
"padding : 2px 10px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.horizontalWidget = QtWidgets.QWidget(self.widget)
        self.horizontalWidget.setGeometry(QtCore.QRect(0, 60, 329, 49))
        self.horizontalWidget.setStyleSheet("background-color : none ;")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setContentsMargins(50, 1, 50, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border : none ;\n"
"background-color : none ;\n"
"\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalWidget)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255) ;\n"
"border-radius : 10px ;\n"
"border : inherit ;\n"
"font-size: 15px ;\n"
"padding : 2px 10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalWidget3 = QtWidgets.QWidget(self.widget)
        self.horizontalWidget3.setGeometry(QtCore.QRect(0, 110, 329, 59))
        self.horizontalWidget3.setStyleSheet("background-color : none ;")
        self.horizontalWidget3.setObjectName("horizontalWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget3)
        self.horizontalLayout_3.setContentsMargins(50, 1, 50, 1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color : none ;\n"
"border : none ;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.spinBox = QtWidgets.QSpinBox(self.horizontalWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBox.setFont(font)
        self.spinBox.setAutoFillBackground(False)
        self.spinBox.setStyleSheet("margin : 0px 10px ; \n"
"padding : 10px 15px ;\n"
"background-color : none ;\n"
"border-radius : 10px;")
        self.spinBox.setProperty("showGroupSeparator", False)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(11)
        self.spinBox.setSingleStep(2)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.horizontalWidget3_2 = QtWidgets.QWidget(self.widget)
        self.horizontalWidget3_2.setGeometry(QtCore.QRect(10, 190, 321, 61))
        self.horizontalWidget3_2.setStyleSheet("background-color : none ;")
        self.horizontalWidget3_2.setObjectName("horizontalWidget3_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalWidget3_2)
        self.horizontalLayout_4.setContentsMargins(50, 1, 50, 1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.horizontalWidget3_2)
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("#pushButton{\n"
"border : 2px inset white ;\n"
"padding : 5px px ;\n"
"background-color : blue ;\n"
"border-radius:10px ;\n"
"}\n"
"\n"
"#pushButton:hover {\n"
"    background-color : green ;\n"
"border : 2px inset white ;\n"
"padding : 5px px ;\n"
"\n"
"border-radius:10px ;\n"
"}")
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(90, 180, 171, 2))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_2, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.spinBox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tic Tac Toc"))
        self.label.setText(_translate("MainWindow", "Jeu de Tic Tac Toe"))
        self.label_3.setText(_translate("MainWindow", "Joueur 1 "))
        self.horizontalWidget.setWhatsThis(_translate("MainWindow", "background-color : none ;\n"
""))
        self.label_2.setText(_translate("MainWindow", "Joueur 2 "))
        self.label_4.setText(_translate("MainWindow", "Nombre de parties"))
        self.pushButton.setText(_translate("MainWindow", "Valider"))

